[build]
  publish = "dist"          # ← No "frontend/" prefix needed
  command = "npm run build" # ← No "cd frontend" needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"